Add rancher-provisioning-capi chart
rancher/provisioning pull request #1
Opened 2023-07-20 20:35 UTC by Oats87

This PR adds a new helm chart to install the rancher-provisioning-capi chart. This chart will end up being included in Rancher through https://github.com/rancher/charts and installed by the dashboard controllers.

Notably, this chart does NOT contain the corresponding webhooks or CRDs, as those are managed directly by Rancher.

Image was mirrored into image-list: https://github.com/rancher/image-mirror/blob/692f166d24383cd99ee96fbb65e7669d68606828/images-list#L1143

https://github.com/rancher/rancher/issues/41094

2023-07-20 21:00 UTC, aiyengar2 requested changes

2023-07-20 21:00 UTC, aiyengar2 commented on charts/capi/values.yaml
> +  - "--metrics-bind-addr=localhost:8080"
also copy this and drop the PSP stuff to take care of hardened https://github.com/rancher/helm-locker/blob/main/charts/helm-locker/templates/hardened.yaml

2023-07-20 21:01 UTC, aiyengar2 commented on .gitignore
> +charts/capi/templates/for-rancher
nvm we should utilize a temporary directory in the scripts and remove this. See comment below.

2023-07-20 21:07 UTC, Oats87 commented on charts/capi/templates/_helpers.tpl
> +{{- define "system_default_registry" -}}
Do I really need a `NOTES.txt` for a chart that's installed in an automated fashion...?

2023-07-20 21:07 UTC, Oats87 commented on charts/capi/templates/clusterrole-capi-aggregated-manager-role.yaml
> +rules: []
This is auto-generated and "how it comes"

2023-07-20 21:08 UTC, Oats87 commented on scripts/create-capi-chart.sh
> +mkdir for-rancher
honestly, I think this is a nit, I tried to document the method of generating the chart through this script, but the script was never meant to be "production grade". No doubt the next bump is going to need manual reconciliation.

2023-07-20 21:08 UTC, Oats87 commented on scripts/create-capi-chart.sh
> +fi
I think this is a nit and not necessary for this PR

2023-07-20 21:09 UTC, Oats87 commented on scripts/create-capi-chart.sh
> +yq -i '.metadata.name = "validating-webhook-configuration"' for-rancher/validatingwebhookconfiguration-capi-validating-webhook-configuration.yaml
I do not want CI running this at this point. This script is more of a documentation of what was changed rather than the new generation script, given we have no control over the "source" assets and how they change from release to release.

2023-07-21 17:14 UTC, aiyengar2 commented on scripts/create-capi-chart.sh
> +yq -i '.metadata.name = "validating-webhook-configuration"' for-rancher/validatingwebhookconfiguration-capi-validating-webhook-configuration.yaml
Can we add it to the README.md for this repository then with instructions to install yq?

2023-07-21 17:16 UTC, aiyengar2 commented on scripts/create-capi-chart.sh
> +mkdir for-rancher
Yeah this is a nit, but I also think the change is pretty small to add inside and is better from a code hygiene perspective. I'll leave this up to you though

2023-07-21 17:23 UTC, aiyengar2 commented on charts/capi/values.yaml
> +  - "--metrics-bind-addr=localhost:8080"
Note: this is not necessary if we plan to deploy in `cattle-system` iirc, so resolve this if that is the case.

2023-07-24 16:26 UTC, aiyengar2 requested changes
Remove PSP stuff since we no longer release charts with PSPs in favor of PSAs, otherwise LGTM

2023-07-24 16:26 UTC, aiyengar2 commented on charts-source/capi/templates/hardened.yaml
> +apiVersion: policy/v1beta1
PSP needs to be removed?

2023-07-24 19:54 UTC, Oats87 commented on .gitignore
> +.idea
copied

2023-07-24 19:54 UTC, Oats87 commented on .gitignore
> +charts/capi/templates/for-rancher
we now use `/dist`

2023-07-24 19:54 UTC, Oats87 commented on charts/capi/Chart.yaml
> +appVersion: v1.4.4
offline convo, moving to non-prefixed version

2023-07-24 19:54 UTC, Oats87 commented on charts/capi/questions.yaml
> +rancher_min_version: 2.7.0-alpha1
used annotation

2023-07-24 19:55 UTC, Oats87 commented on charts/capi/Chart.yaml
> +kubeVersion: '>= 1.23.0-0'
added maintainer as myself

2023-07-24 19:55 UTC, Oats87 commented on scripts/create-capi-chart.sh
> +mkdir for-rancher
changed logic to be able to run from repo root

2023-07-24 19:55 UTC, Oats87 commented on scripts/create-capi-chart.sh
> +yq -i '.metadata.name = "validating-webhook-configuration"' for-rancher/validatingwebhookconfiguration-capi-validating-webhook-configuration.yaml
changed to using dapper

2023-07-24 19:55 UTC, Oats87 commented on charts-source/capi/templates/hardened.yaml
> +apiVersion: policy/v1beta1
removed PSP

2023-07-24 20:21 UTC, aiyengar2 approved these changes

2023-07-24 20:21 UTC, aiyengar2 commented on charts-source/capi/templates/hardened.yaml
> +---
nit: extra newline

2023-07-24 20:23 UTC, aiyengar2 approved these changes
LGTM

2023-07-25 20:12 UTC, jakefhyde approved these changes

2023-07-25 20:23 UTC, merged