CAPI v1.7.2
rancher/provisioning pull request #11
Opened 2024-06-11 02:48 UTC by vardhaman22

issue: https://github.com/rancher/rancher/issues/45089
-  bumping the version since capi v1.7.x officially supports v1.30.

2024-06-12 19:13 UTC, jakefhyde requested changes
How extensively have we tested v1.7.3 vs. v1.6.4? There are a few changes in the changelog for v1.7.0 that I want to make sure we've tested against beforehand.

2024-06-12 19:13 UTC, jakefhyde commented on scripts/capi-chart
> +CAPI_VERSION=v1.7.2
Should this be

```suggestion
CAPI_VERSION=v1.7.3
```

2024-06-13 13:13 UTC, vardhaman22 commented on scripts/capi-chart
> +CAPI_VERSION=v1.7.2
thanks for pointing it out.
updated.

2024-06-13 13:16 UTC, vardhaman22 commented
> How extensively have we tested v1.7.3 vs. v1.6.4? There are a few changes in the changelog for v1.7.0 that I want to make sure we've tested against beforehand.

i have tested basic provisioning and cluster upgrade scenarios and updated description in the PR: https://github.com/rancher/rancher/pull/45483
please let me know if i should test more scenarios. I did the testing with 1.7.2

2024-06-17 20:29 UTC, jakefhyde commented
@vardhaman22 @chiukapoor If we could test etcd snapshot & restore, encryption key rotation, certificate rotation, and some machine scaling operations (scaling from 3 -> 1 -> 3) for 3 nodes all roles and a 3 etcd, 2 controlplane, 3 worker setup, I'd feel a lot more comfortable as those are typically the areas where we see regressions. Alternatively, if you can run `make provisioning-tests` within Rancher on 1.30 for RKE2 and K3s, that would also suffice since we test those cases as well, although the tests themselves have been somewhat flaky as of late.

2024-06-20 05:02 UTC, merged