[v1.28] Update CAPI, golang, rancher/kubectl versions and feature flag
rancher/provisioning pull request #3
Opened 2024-01-23 13:24 UTC by chiukapoor

### Update
* CAPI to 1.5.5 
* golang to 1.20
* rancher/kubectl to v1.23.3
* Remove `LazyRestmapper` feature flag for capi v4 to v5 migration, [Context](https://cluster-api.sigs.k8s.io/developer/providers/migrations/v1.4-to-v1.5#removals).

### Related
* https://github.com/rancher/rancher/issues/43109

2024-01-24 18:17 UTC, jakefhyde requested changes

2024-01-25 05:09 UTC, chiukapoor commented on charts-source/capi/values.yaml
> +  repository: csociety/mirrored-cluster-api-controller
Sorry, for leaving that around.

 Updated it.

2024-01-30 17:18 UTC, Oats87 commented on charts-source/capi/Chart.yaml
> +appVersion: "1.5.5"
are we specifically bumping the minor version of `cluster-api` to satisfy the `1.28` support change?

2024-01-31 11:02 UTC, chiukapoor commented on charts-source/capi/Chart.yaml
> +appVersion: "1.5.5"
Yes

2024-01-31 18:12 UTC, jakefhyde approved these changes

2024-01-31 18:13 UTC, jakefhyde commented on charts-source/capi/values.yaml
> +    tag: v1.28.5
Huh, out of curiosity any idea why the big jump here?

2024-02-01 04:37 UTC, chiukapoor commented on charts-source/capi/values.yaml
> +    tag: v1.28.5
Updated the `rancher/kubectl` to latest to match with the 1.28 Kubernetes support bump.

2024-02-09 19:11 UTC, Oats87 approved these changes
Approving as generally the changes look sane to me, but please examine the comments as there are action items within them that should be taken care of before actually merging.

2024-02-09 19:11 UTC, Oats87 commented on charts-source/capi/Chart.yaml
> +appVersion: "1.5.5"
Looking here: https://cluster-api.sigs.k8s.io/developer/providers/migrations/v1.4-to-v1.5

One of the major concerns I have is around the removal of `v1alpha3` and serve disabling of `v1alpha4`. I don't see any references to `v1alpha3` or `v1alpha4` in our codebase other than a few issues surrounding warnings that were getting served due to `v1alpha3`: see https://github.com/rancher/rancher/issues/43083

2024-02-12 10:36 UTC, chiukapoor commented on charts-source/capi/values.yaml
> +    tag: v1.28.5
Sure @Oats87, I will update this PR and parent issue with the QA testing considerations for this PR.

2024-02-13 12:03 UTC, chiukapoor commented on charts-source/capi/Chart.yaml
> +appVersion: "1.5.5"
Checking on this with @kinarashah

2024-02-13 19:36 UTC, snasovich commented on charts-source/capi/Chart.yaml
> +appVersion: "1.5.5"
> Have we investigated the differences in release notes between these versions?
> 
> I'm concerned about the potential behavioral differences moving from one minor to another minor of CAPI within a patch release line of Rancher.
> 
> Do we have an official exception here to confirm that this is OK?

Yes, adding support for new K8s versions in a patch is agreed upon exception and since bumping CAPI is needed for that it covered too.

2024-02-13 20:02 UTC, merged

2024-03-04 22:38 UTC, Oats87 commented on charts-source/capi/values.yaml
> +    tag: v1.28.5
To clarify, the way to test this is to install Rancher onto a hardened "local" cluster.

2024-03-05 06:09 UTC, chiukapoor commented on charts-source/capi/values.yaml
> +    tag: v1.28.5
Thanks @Oats87 for clarifying.

cc: @vivek-shilimkar

2024-03-06 10:58 UTC, vivek-shilimkar commented
Tested installing Rancher chart on local hardened cluster (RKE1, RKE2, and K3S) with minimum supported k8s version (v1.25).